(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'bs-12',
          componentName:'ContactFormHours',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:false
        });
      })({"structuredHours":[{"hour":{"day":"Monday","dayOfWeek":1,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"Tuesday","dayOfWeek":2,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"Wednesday","dayOfWeek":3,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"Thursday","dayOfWeek":4,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"Friday","dayOfWeek":5,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"Saturday","dayOfWeek":6,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":true}},{"hour":{"day":"Sunday","dayOfWeek":0,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":true}}],"staticContent":{"today":"Today","submitButtonLoadingLabel":"Sending","contactFormResponseErrorMessage":"Something went wrong while sending your message, please try again later","phoneValidationErrorMessage":"Please enter a valid phone number.","defaultCancelButtonLabel":"Cancel","byAppointment":"By Appointment","defaultSubmitButtonLabel":"Send","unsupportedFileType":"Unsupported file type","maxFileCountLimit":"Only {0} files are allowed","closed":"Closed","attachments":"Attachments","termsOfSerivce":"Terms of Service","attachFiles":"Attach Files","recaptchaDisclosure":"This site is protected by reCAPTCHA and the Google {privacyPolicy} and {termsOfSerivce} apply.","emailValidationErrorMessage":"Please enter a valid email address.","mapCTA":"Get directions","privacyPolicyURL":"https:\u002F\u002Fpolicies.google.com\u002Fprivacy","requiredValidationErrorMessage":"Please fill in this required field","openToday":"Open today","couldNotAttach":"Could not attach the following file(s)","totalFileSizeLimit":"Total files would exceed {0} limit","privacyPolicy":"Privacy Policy","termsOfSerivceURL":"https:\u002F\u002Fpolicies.google.com\u002Fterms","fileSizeLimit":"File exceeds {0} limit","emailMaxCountValidationErrorMessage":"Your email address is too long"},"collapsible":true,"widgetId":"ad428df9-360f-4c9b-89a8-806955669deb","section":"alt","category":"neutral","locale":"en-GB","renderMode":"PUBLISH"},{"widgetId":"ad428df9-360f-4c9b-89a8-806955669deb","widgetType":"CONTACT","widgetPreset":"contact3","order":7,"section":"alt","category":"neutral","fontSize":"medium","fontFamily":"alternate","group":"Content","groupType":"Default","websiteThemeOverrides":{},"widgetThemeOverrides":{}});