(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'bs-6',
          componentName:'@widget/LAYOUT/bs-MobileFlyoutMenu-Component',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:"@widget/LAYOUT/bs-MobileFlyoutMenu-Component"
        });
      })({"item":{"isFlyoutMenu":true,"active":false,"pageId":"72b7c586-f1c0-493a-ab70-ada52aabb61b","name":"HEALTH GUARANTEE","href":"\u002Fhealth-guarantee","target":"","visible":true,"navigation":[{"isFlyoutMenu":false,"active":true,"pageId":"20b9d113-1378-4d74-9434-4a61e823ecf5","name":"Breed Information","href":"\u002Fbreed-information-1","target":"","visible":true,"requiresAuth":false,"tags":[],"rel":"","type":"page","showInFooter":false}],"requiresAuth":false,"tags":[],"rel":"","type":"page","showInFooter":false},"styles":{"mobileOnly":{"@xs":{"display":"block"},"@md":{"display":"none"}},"overlay":{"position":"fixed","overflow":"hidden","display":"flex","flexDirection":"column"},"innerContainer":{"overflowY":"auto","overflowX":"hidden","width":"100%"},"topContainer":{"paddingHorizontal":"medium"},"membershipHeader":{"paddingBottom":"large"},"close":{"position":"absolute","top":15,"right":15,"fontSize":"xlarge"},"list":{"textAlign":"left","paddingVertical":"0","paddingHorizontal":"0","wordWrap":"break-word","overflowWrap":"break-word"},"subList":{"paddingHorizontal":"0","paddingTop":"0","paddingBottom":"small"},"subListItem":{"display":"block","marginBottom":"0","borderBottomWidth":"0",":last-child":{"paddingBottom":"medium"}},"socialContainer":{"display":"flex","justifyContent":"flex-start","alignItems":"center","marginBottom":"large","flexDirection":"column","\u003E :not(:first-child)":{"marginTop":"small"}},"searchFormContainer":{"position":"relative","height":"auto"},"translateContainer":{"@md":{"display":"none"}}},"domainName":"lissasmoyedhomes.com","pageRoute":"\u002Fbreed-information-1","widgetId":"fb87003f-bf71-4509-ba80-c162cc8bebc9","section":"default","category":"accent","locale":"en-GB","renderMode":"PUBLISH"},{"widgetId":"fb87003f-bf71-4509-ba80-c162cc8bebc9","widgetType":"HEADER","widgetPreset":"header9","section":"default","category":"accent","fontSize":"medium","fontFamily":"alternate","group":"NavigationDrawer","groupType":"Default","websiteThemeOverrides":{},"widgetThemeOverrides":{}});